### PR TITLE
enforce that the trailing bits of an address string are standard

### LINKED ISSUE #22: Enforce a padding scheme
Because we don't enforce a padding scheme, we have `f1xpbyy4tkdx5si2bgo37dubc2xwv6fum5tk57mid` and `f1xpbyy4tkdx5si2bgo37dubc2xwv6fum5tk57mia` "actually" being the same address.

This isn't the easiest thing to fix, since we currently operate with "no padding",  but the solution is probably to refuse to decode other padding schemes:

- decode string X to address A
- re-encode address A to string X'
- fail if X not equal to X'

### PR DESCRIPTION
**Pull request by arajasek**
Fixes #22

### CODE REVIEW

File: address.go [hunk 1]
```diff
@@ -323,6 +323,11 @@ func decode(a string) (Address, error) {
 		return Undef, err
 	}
 
+	reencodedRaw := AddressEncoding.WithPadding(-1).EncodeToString(payloadcksm)
+	if reencodedRaw != raw {
+		return Undef, ErrInvalidChecksum
```
Comment (Stebalien) [inline address.go]: We should make a new error. The checksum isn't invalid, it's just not a "standard" encoding.

**Review by Stebalien — APPROVED** [review]

File: address.go (hunk 1 above)
Comment (arajasek) [reply address.go]: Yeah, I was too lazy to do that. Done.
